### ISSUE TITLE
Dúvida sobre o programa. 

### ISSUE THREAD

**Issue by PH-Vieira** [holyrics/JSCommunity#28]
Olá, eu sei que esse não é o lugar correto pra isso, mas não consigo encontrar informação sobre em lugar algum.

Eu preciso montar um computador só pra rodar o holyrics, vcs conseguem me ajudar com os requisitos mínimos pra isso?

**Comment by holyrics** [comment]
[https://holyrics.com.br/faq#q014](https://holyrics.com.br/faq#q014)
